# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  # TODO: running test only for PR
  test:
    docker:
      - image: circleci/golang:1.14.4
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    resource_class: small
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  # running test-build-deploy only for merged commit in master and circle-ci branch
  test-build-deploy:
    docker:
      - image: circleci/golang:1.14.4
    resource_class: small
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: make build
      - add_ssh_keys:
          fingerprints:
            - "30:f5:3e:ca:30:b7:02:23:2e:59:de:ae:17:b0:18:79"
      - run: sudo apt install sshpass
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/500.html $SSH_USER@$SSH_HOST:~/pos.pikomo.top
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/.htaccess $SSH_USER@$SSH_HOST:~/pos.pikomo.top
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" -r /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/setup $SSH_USER@$SSH_HOST:~/pos.pikomo.top
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/config/local.yaml $SSH_USER@$SSH_HOST:~/pos.pikomo.top/config
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/run.sh $SSH_USER@$SSH_HOST:~/pos.pikomo.top
      - run: sshpass -p $SSH_PASS scp -P $SSH_PORT -o "StrictHostKeyChecking no" /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/service_pikopos $SSH_USER@$SSH_HOST:~/pos.pikomo.top
      - run: sshpass -p $SSH_PASS ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST -p $SSH_PORT /usr/bin/sh /home/pikomoto/pos.pikomo.top/run.sh

workflows:
  version: 2
  wf-test-build-deploy:
    jobs:
      - test-build-deploy:
          context: org-global
          filters:
            branches:
              only: /^((((test|fix)/)?circle-ci.*)|(master$))/ # only deploy on the merge of master branch and circle-ci branch
