MySQLPikopos: 'root:pass@/pikopos'
JWTSecret: 'NJKNSJKAJNJADNJ@2nwjscnd323'

BaseURL: '073d8bef44a6.ngrok.io'

OAuth:
  google:
    ClientID: ''
    ClientSecret: ''
    Scopes:
      - 'https://www.googleapis.com/auth/userinfo.email'
      # - 'https://www.googleapis.com/auth/userinfo.profile'
  facebook:
    ClientID: ''
    ClientSecret: ''
    Scopes:
